// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isdatgpynfrhovckcyhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzZGF0Z3B5bmZyaG92Y2tjeWhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMzU2MzQsImV4cCI6MjA2NDgxMTYzNH0.DhizJejuoofa3JRurH0JKfbS4oBt89rqjBbAp0LU5lI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);